### ISSUE TITLE
Add Bucket Sort in Java

### ISSUE THREAD

**Issue by shashwatj07** [shashwatj07/scripts#2]
Add the bucket sort algorithm.

**Comment by aastha01chauhan** [comment]
Sir, I am a beginner, please assign this issue to me🥺

**Comment by shashwatj07** [comment]
fix is merged

**Comment by SamikshyaMstar** [comment]
Can I add quick sort in java? @shashwatj07

**Comment by shashwatj07** [comment]
> Can I add quick sort in java? @shashwatj07

Sure! Please open the issue and send PR. Don't wait for approval or assignment.

**Comment by SamikshyaMstar** [comment]
> > Can I add quick sort in java? @shashwatj07
> 
> Sure! Please open the issue and send PR. Don't wait for approval or assignment.

I saw your text late and without opening an issue I sent PR . Kindly consider my PR @shashwatj07.
